FROM alpine:3.3

RUN apk add --update build-base pcre-dev openssl-dev zlib-dev \
  && rm -rf /var/cache/apk/*

WORKDIR /tmp
RUN wget http://nginx.org/download/nginx-1.8.1.tar.gz \
  && tar xzf nginx-1.8.1.tar.gz

WORKDIR nginx-1.8.1
RUN ./configure \
    --with-http_gzip_static_module \
    --with-http_realip_module \
    --with-http_ssl_module \
  && make \
  && make install

COPY nginx /etc/init.d/
RUN chmod +x /etc/init.d/nginx

EXPOSE 80
