FROM ubuntu:14.04

RUN apt-get -y update \
  && apt-get -y install build-essential libpcre3-dev libssl-dev zlib1g-dev wget \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp
RUN wget http://nginx.org/download/nginx-1.8.1.tar.gz \
  && tar xzf nginx-1.8.1.tar.gz

WORKDIR nginx-1.8.1
RUN ./configure \
    --with-http_gzip_static_module \
    --with-http_realip_module \
    --with-http_ssl_module \
  && make \
  && make install

COPY nginx /etc/init.d/
RUN chmod +x /etc/init.d/nginx \
  && update-rc.d nginx defaults
